import { describe,it } from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import { createWorld, validateState, give, count, craft, planNight, transactTransfer, addItem } from '../lib/game/model';
import { tierCap,MONSTERS,RECIPES } from '../lib/game/data';
import { SaveManager,pack,unpack } from '../lib/game/storage';
import { Engine } from '../lib/game/engine';
describe('world and game transactions',()=>{
it('same seed produces identical resources',()=>{const a=createWorld('A','deterministic'),b=createWorld('B','deterministic');assert.deepEqual(a.nodes,b.nodes);assert.ok(a.nodes.filter(n=>n.kind==='iron'&&Math.hypot(n.x,n.z)<200).length>=4);assert.equal(validateState(a).seed,a.seed)});
it('crafting cannot lose materials when output space is unavailable',()=>{const s=createWorld('A','1');s.player.items=[];give(s.player.items,'wood',20);for(let i=0;i<23;i++)give(s.player.items,'stone_axe',1);const before=structuredClone(s.player.items);const r=RECIPES.find(r=>r.id==='workbench')!;assert.ok(craft(s,r));assert.deepEqual(s.player.items,before)});
it('crafting consumes inputs and creates output once',()=>{const s=createWorld('A','1');addItem(s,'wood',10);assert.equal(craft(s,RECIPES.find(r=>r.id==='workbench')!),null);assert.equal(count(s.player.items,'wood'),0);assert.equal(count(s.player.items,'workbench'),1);assert.ok(craft(s,RECIPES.find(r=>r.id==='workbench')!))});
it('transfer is atomic when the target is full',()=>{const a:any[]=[],b:any[]=[];give(a,'stone_pick',1);give(b,'iron_sword',1);const before=structuredClone(a);assert.equal(transactTransfer(a,b,a[0].uid,1),false);assert.deepEqual(a,before)});
it('night plans respect days, species tiers and limits',()=>{for(let day=1;day<30;day++){const s=createWorld('A','seed'+day);s.time=(day-1)*720+510;s.previousKills=500;planNight(s);assert.ok(s.nightPlan.some(e=>e.kind==='zombie'));assert.ok(s.nightPlan.length<=20);for(const e of s.nightPlan){assert.ok(e.tier<=tierCap(day));assert.ok(e.tier>=MONSTERS[e.kind].min);assert.ok(e.tier<=MONSTERS[e.kind].max)}if(day===1)assert.ok(s.nightPlan.every(e=>e.tier===1));if(day<4)assert.ok(s.nightPlan.every(e=>MONSTERS[e.kind].role!=='magic'))}});
it('forge reservations survive reload without awarding twice',()=>{const s=createWorld('A','seed');addItem(s,'iron_ore',4);const b={id:crypto.randomUUID(),kind:'furnace',x:0,z:8,yaw:0,hp:200,items:[],jobs:[],fuel:20};s.buildings.push(b);assert.equal(craft(s,RECIPES.find(r=>r.id==='iron')!),null);assert.equal(count(s.player.items,'iron_ore'),2);const restored=validateState(JSON.parse(JSON.stringify(s)));const e=new Engine(restored,new SaveManager());e.resume();for(let i=0;i<301;i++)e.step(1/30);assert.equal(count(restored.buildings.at(-1)!.items,'iron'),1);assert.equal(restored.buildings.at(-1)!.jobs.length,0);e.dispose()});
it('defeating an enemy twice does not duplicate a reward',()=>{const s=createWorld('A','seed');const enemy=s.enemies[0];const engine=new Engine(s,new SaveManager());engine.hitEnemy(enemy,100,'iron_sword');engine.hitEnemy(enemy,100,'iron_sword');assert.equal(s.drops.length,1);engine.dispose()});
it('paused simulation never advances offline time',()=>{const s=createWorld('A','seed');const engine=new Engine(s,new SaveManager());engine.step(1000);assert.equal(s.time,0);engine.dispose()});
});
describe('browser save integrity',()=>{
it('checksum rejects modification',async()=>{const s=createWorld('A','export');const p=await pack(s);assert.deepEqual(await unpack(p),s);p.state.player.hp=1;await assert.rejects(()=>unpack(p),/체크섬/)});
it('commit, restore, retain three generations and detect old writes',async()=>{const a=new SaveManager(),s=createWorld('save test','save');await a.open();await a.acquire(s.id);for(let i=0;i<4;i++){s.time=i*30;await a.save(s)}const worlds=await a.list();assert.equal(worlds.find(w=>w.id===s.id)!.generation,4);const record=await a.load(s.id);assert.equal(record.state.time,90);const tx=a.db!.transaction('snapshots','readonly');const req=tx.objectStore('snapshots').index('world').getAll(s.id);const records=await new Promise<any[]>(r=>req.onsuccess=()=>r(req.result));assert.equal(records.length,3);const old=structuredClone(s);old.generation=1;await assert.rejects(()=>a.save(old),/충돌/);await a.release();a.close()});
it('latest corrupted save recovers earlier valid generation',async()=>{const a=new SaveManager(),s=createWorld('recover','r');await a.acquire(s.id);s.time=10;await a.save(s);s.time=20;await a.save(s);await new Promise<void>((resolve,reject)=>{const tx=a.db!.transaction('snapshots','readwrite'),store=tx.objectStore('snapshots'),r=store.get([s.id,2]);r.onsuccess=()=>{const v=r.result;v.data.state.time=999;store.put(v)};tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error)});const loaded=await a.load(s.id);assert.equal(loaded.recovered,true);assert.equal(loaded.state.time,10);assert.equal(loaded.state.generation,2);await a.release();a.close()});
it('another owner cannot acquire a live world',async()=>{const a=new SaveManager(),b=new SaveManager(),s=createWorld('lock','l');await a.acquire(s.id);await a.save(s);await assert.rejects(()=>b.acquire(s.id),/다른 탭/);await a.release();await b.acquire(s.id);const loaded=await b.load(s.id);assert.equal(loaded.state.id,s.id);await b.release();a.close();b.close()});
it('invalid inventory numbers and duplicate identities are rejected',()=>{const s=createWorld('A','i');addItem(s,'wood',10);s.player.items[0].qty=-1;assert.throws(()=>validateState(s),/아이템/);s.player.items[0].qty=10;s.player.items.push(structuredClone(s.player.items[0]));assert.throws(()=>validateState(s),/중복/)})
});
